### PR TITLE
Added support for Ubuntu 16.04 (xenial)

### PR DESCRIPTION
**Pull request by joaocc**

### CODE REVIEW

**Comment by William-Yeh** [comment]
Currently the official Ansible repo doesn't support Xenial directly (see http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/ ).

To install the most up-to-date Ansible on Xenial, you'll need to use `pip install ansible`.

**Comment by joaocc** [comment]
Hi.
I also found that out. This is why I installed ansible via apt-get.
On Xenial, it seems to be up to date (http://packages.ubuntu.com/search?keywords=ansible&searchon=names&suite=xenial&section=all).
Or are you concerned with future updates to ansible not being available here?
Thx

**Comment by joaocc** [comment]
Also, installing from apt-get is cleaner - installing pip installs many other packages.

**Comment by William-Yeh** [comment]
It will install Ansible 2.0.0.2-2, instead of 2.0.2.0.

Anyway, I'll use the way you've suggested.

**Comment by joaocc** [comment]
You are correct. If you prefer installing via python-pip, I can try to see how to do a proper cleanup at the end of the build.

**Pull request closed without merging**
